# Redlib systemd service configuration
# See the README or `.env.example` for an explanation of the options
#ADDRESS=127.0.0.1
#PORT=8080
#REDLIB_SFW_ONLY=off
#REDLIB_BANNER=
#REDLIB_ROBOTS_DISABLE_INDEXING=off
#REDLIB_PUSHSHIFT_FRONTEND=undelete.pullpush.io
#REDLIB_ENABLE_RSS=off
#REDLIB_FULL_URL=

#REDLIB_DEFAULT_THEME=system
#REDLIB_DEFAULT_FRONT_PAGE=default
#REDLIB_DEFAULT_LAYOUT=card
#REDLIB_DEFAULT_WIDE=off
#REDLIB_DEFAULT_POST_SORT=hot
#REDLIB_DEFAULT_COMMENT_SORT=confidence
#REDLIB_DEFAULT_BLUR_SPOILER=off
#REDLIB_DEFAULT_SHOW_NSFW=off
#REDLIB_DEFAULT_BLUR_NSFW=off
#REDLIB_DEFAULT_USE_HLS=off
#REDLIB_DEFAULT_HIDE_HLS_NOTIFICATION=off
#REDLIB_DEFAULT_AUTOPLAY_VIDEOS=off
#REDLIB_DEFAULT_SUBSCRIPTIONS=
#REDLIB_DEFAULT_HIDE_AWARDS=off
#REDLIB_DEFAULT_HIDE_SIDEBAR_AND_SUMMARY=off
#REDLIB_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION=off
#REDLIB_DEFAULT_HIDE_SCORE=off
#REDLIB_DEFAULT_FIXED_NAVBAR=on
#REDLIB_DEFAULT_REMOVE_DEFAULT_FEEDS=off
#REDLIB_DEFAULT_CLEAN_URLS=off
#REDLIB_DEFAULT_POSTS_PER_PAGE=25
#REDLIB_DEFAULT_MAX_COMMENT_THREAD_DEPTH=0
