#!/bin/bash

# Requirements
# - curl
# - rg
# - jq

# Specify the filename as a variable
filename="src/oauth_resources.rs"

# Add comment that it is user generated
echo "// This file was generated by scripts/update_oauth_resources.sh" > "$filename"
echo "// Rerun scripts/update_oauth_resources.sh to update this file" >> "$filename"
echo "// Please do not edit manually" >> "$filename"
echo "// Filled in with real app versions" >> "$filename"

# User agents for APKMirror requests - AI assistants and search engines
USER_AGENTS=(
	"Mozilla/5.0 (compatible; archive.org_bot +http://www.archive.org/details/archive.org_bot)"
	"ia_archiver (+http://www.alexa.com/site/help/webmasters; crawler@alexa.com)"
	"Wayback Machine Bot/1.0"
)

# Function to get a random user agent
get_random_user_agent() {
	echo "${USER_AGENTS[$RANDOM % ${#USER_AGENTS[@]}]}"
}

# Fetch Android app versions from APKMirror
page_1=$(curl -s -H "User-Agent: $(get_random_user_agent)" "https://www.apkmirror.com/uploads/?devcategory=redditinc" | rg 'href="(/apk/redditinc/reddit/reddit-[0-9]+-[0-9]+-[0-9]+-release/)"' -o -r "https://www.apkmirror.com\$1" | sort -u)
page_2=$(curl -s -H "User-Agent: $(get_random_user_agent)" "https://www.apkmirror.com/uploads/page/2/?devcategory=redditinc" | rg 'href="(/apk/redditinc/reddit/reddit-[0-9]+-[0-9]+-[0-9]+-release/)"' -o -r "https://www.apkmirror.com\$1" | sort -u)

# Concatenate all pages
versions="${page_1}\n{page_2}"

# Count the number of lines in the version list
android_count=$(echo "$versions" | wc -l)

echo -e "Fetching \e[32m$android_count Android app versions...\e[0m"

# Append to the source file
echo "pub const ANDROID_APP_VERSION_LIST: &[&str; $android_count] = &[" >> "$filename"

num=0

# For each in versions, curl the page and extract the build number
echo "$versions" | while IFS= read -r line; do
	num=$((num+1))
	fetch_page=$(curl -s -H "User-Agent: $(get_random_user_agent)" "$line")
	build=$(echo "$fetch_page" | rg 'class="colorLightBlack">([0-9]+)</span>' -o -r '$1' | head -n1)
	# Extract version from URL instead of HTML to get the correct version for this specific release
	version=$(echo "$line" | rg 'reddit-([0-9]+-[0-9]+-[0-9]+)-release' -o -r '$1' | sed 's/-/./g')
	echo "	\"Version $version/Build $build\"," >> "$filename"
	echo -e "[$num/$android_count] Fetched \e[32mVersion $version/Build $build\e[0m."
	sleep 30
done

# Close the array in the source file
echo "];" >> "$filename"

echo -e "\e[32mRetrieved $android_count Android app versions.\e[0m"
echo -e "\e[32mSuccess!\e[0m"
